### ISSUE TITLE
compute_tidal_elevations.py --type=grid fails with shape mismatch

### ISSUE THREAD

**Issue by bjarnebuchmann** [tsutterley/pyTMD#154]
compute_tidal_elevations.py --type=grid --format=netCDF4 fails with shape mismatch before writing output.

To keep this issue simple, I have created a dummy input file with points (lat,lon,time) to be interpolated:

```
cat << EOF | tee pytmd_tll.cdl
netcdf pytmd_tll {
dimensions:
        time = 7 ;
        lat = 10;
        lon = 2;
variables:
        float lon(lon) ;
                lon:_FillValue = -9999.f ;
                lon:long_name = "longitude at T-points (cell centres)" ;
                lon:units = "degrees-east" ;
        float lat(lat) ;
                lat:_FillValue = -9999.f ;
                lat:long_name = "latitude at T-points (cell centres)" ;
                lat:units = "degrees-north" ;
        float time(time) ;
                time:_FillValue = -9999.f ;
                time:missing_value = -9999. ;
                time:long_name = "time" ;
                time:units = "seconds since 2021-01-30 00:00" ;
data:

lon = -51.88087, -51.88676 ;

lat = 63.08587, 63.09052, 63.09517, 63.09982, 63.10447, 63.10912, 63.11377,  63.11841, 63.12306, 63.12771 ;

time = 0., 600., 1200., 1800., 2400., 3000., 3600.;
}
EOF
cat pytmd_tll.cdl | ncgen -3  -o pytmd_tll.nc
```
I've used arcticdata_tides.py to download Gr1kmTM to ensure that I have the right data and the right format.
I use the latest code update (git), so that I do not need to specify "data" (4th varname).
My command line looks like:

```
python3 /home/bjb/pyTDM/install-2023-01-31/bin/compute_tidal_elevations.py --directory=/mnt/nfs/modeldev02-scratch/bjb_today/TDMdata --tide=Gr1kmTM --format=netCDF4 --type=grid --variables time lat lon --projection 4326 pytmd_tll.nc pytdm-test.nc
```

I have tested (debug/write statements), that the program does set up a tide-array of shape `(ny,nx,nt)=(10,2,7)`, and it contains data.
However, there is an error when output is defined:

```
Traceback (most recent call last):
  File "/home/bjb/pyTDM/install-2023-01-31/bin/compute_tidal_elevations.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyTMD==2.0.1.dev8+g664d6c0.d20230131', 'compute_tidal_elevations.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/bjb/pyTDM/install-2023-01-31/lib/python3.10/site-packages/pyTMD-2.0.1.dev8+g664d6c0.d20230131-py3.10.egg/EGG-INFO/scripts/compute_tidal_elevations.py", line 553, in <module>
    main()
  File "/home/bjb/pyTDM/install-2023-01-31/lib/python3.10/site-packages/pyTMD-2.0.1.dev8+g664d6c0.d20230131-py3.10.egg/EGG-INFO/scripts/compute_tidal_elevations.py", line 530, in main
    compute_tidal_elevations(args.directory, args.infile, args.outfile,
  File "/home/bjb/pyTDM/install-2023-01-31/lib/python3.10/site-packages/pyTMD-2.0.1.dev8+g664d6c0.d20230131-py3.10.egg/EGG-INFO/scripts/compute_tidal_elevations.py", line 398, in compute_tidal_elevations
    pyTMD.spatial.to_netCDF4(output, attrib, output_file)
  File "/home/bjb/pyTDM/install-2023-01-31/lib/python3.10/site-packages/pyTMD-2.0.1.dev8+g664d6c0.d20230131-py3.10.egg/pyTMD/spatial.py", line 682, in to_netCDF4
    nc[key][:] = val
  File "src/netCDF4/_netCDF4.pyx", line 4903, in netCDF4._netCDF4.Variable.__setitem__
  File "/usr/lib/python3/dist-packages/netCDF4/utils.py", line 356, in _StartCountStride
    datashape = broadcasted_shape(shape, datashape)
  File "/usr/lib/python3/dist-packages/netCDF4/utils.py", line 964, in broadcasted_shape
    return np.broadcast(a, b).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

If I am doing something completely wrong, then feel free to just point me in the right direction.

Thanks,
Bjarne

**Comment by tsutterley** [comment]
This has been a long standing but undocumented issue. Thanks for getting it back on my radar. Because netCDF files have named dimensions, I had only the `drift` case working.  This should be fixed with #159
